import test from "node:test";
import assert from "node:assert/strict";
import { BASKET_MARGIN_FRACTIONS, STRATEGY_VERSION, TIMEFRAMES, createSimulator, migrateSimulator, processSimulator } from "../simulator.js";
import { WEIGHTS } from "../strategy.js";
const parts=Object.fromEntries(Object.keys(WEIGHTS).map(k=>[k,.25]));
const c=(time=1,closeTime=6000000,open=100,high=101,low=99,close=100)=>({time,closeTime,open,high,low,close,volume:100,quoteVolume:10000});
const history=(bar=c())=>Array.from({length:100},(_,i)=>({...bar,closeTime:bar.closeTime-(99-i)*60000,time:bar.closeTime-(100-i)*60000+1}));
const current=(score=80,ct=6000000,price=100)=>Object.fromEntries(TIMEFRAMES.map(tf=>[tf,{long:score,short:100-score,close:price,closeTime:ct,parts,hist:.1,rsi:50}]));
const open=(score=80)=>{const s=createSimulator();processSimulator(s,current(score),{"1m":history()});return s;};
function canonicalFull(side="long") {const s=open(side==="long"?80:20),p=s.position;p.legs=[];p.totalMargin=p.totalNotional=p.entryFeesPaid=p.feesPaid=0;BASKET_MARGIN_FRACTIONS.forEach((f,i)=>{const margin=1000*f,notional=margin*10,fillPrice=side==="long"?100+i:100-i,entryFee=notional*.002,rawPrice=side==="long"?fillPrice/1.001:fillPrice/.999;p.legs.push({index:i+1,marginFraction:f,margin,leverage:10,notional,remainingNotional:notional,fillPrice,rawPrice,time:6000000,entryFee,zoneEvidence:null});p.totalMargin+=margin;p.totalNotional+=notional;p.entryFeesPaid+=entryFee;p.feesPaid+=entryFee;});p.remainingNotional=p.totalNotional;p.remainingFraction=1;p.weightedAverage=p.legs.reduce((n,l)=>n+l.fillPrice*l.notional,0)/p.totalNotional;p.entry=p.weightedAverage;p.capital=p.totalMargin;s.bank=1000-p.entryFeesPaid;return migrateSimulator(JSON.parse(JSON.stringify(s)));}

test("terminal 1m identity mismatch fails closed",()=>{const s=createSimulator();const m=current();m["1m"].closeTime=59999;assert.equal(processSimulator(s,m,{"1m":history()}).invalidData,true);assert.equal(s.position,null);});
test("future 5m context fails closed",()=>{const s=createSimulator(),m=current();m["5m"].closeTime=6000001;assert.equal(processSimulator(s,m,{"1m":history()}).invalidData,true);});
test("stale 5m context fails closed",()=>{const s=createSimulator(),m=current();m["5m"].closeTime=1;const bar=c(300001,360000);Object.values(m).forEach(x=>x.closeTime=360000);m["5m"].closeTime=1;assert.equal(processSimulator(s,m,{"1m":[bar]}).invalidData,true);});
test("weak setup requires fresh macro available at decision",()=>{const weak=current(70);for(const macro of [undefined,{score:90,stale:true,availableFrom:1},{score:90,stale:false,availableFrom:6000001},{score:90,stale:false,availableFrom:1-1800001}]){const s=createSimulator();processSimulator(s,weak,{"1m":history()},{macroSnapshot:macro});assert.equal(s.position,null);}const s=createSimulator();processSimulator(s,weak,{"1m":history()},{macroSnapshot:{score:90,stale:false,availableFrom:5999000}});assert.ok(s.position);});
test("macro score below 80 cannot enable weak setup",()=>{const s=createSimulator();processSimulator(s,current(70),{"1m":history()},{macroSnapshot:{score:79,stale:false,availableFrom:5999000}});assert.equal(s.position,null);});
test("first leg modeled liquidation is remote and does not mimic an 0.8% loss stop",()=>{const p=open().position;assert.ok(p.liquidationBoundary>0&&p.liquidationBoundary<10);assert.ok(p.riskBoundary<p.weightedAverage*.1);});
test("full long risk boundary dominates modeled liquidation",()=>{const p=canonicalFull("long").position;assert.ok(p.riskBoundary>p.liquidationBoundary);assert.ok(p.riskBoundary>90);});
test("full short risk boundary dominates modeled liquidation",()=>{const p=canonicalFull("short").position;assert.ok(p.riskBoundary<p.liquidationBoundary);assert.ok(p.riskBoundary<110);});
test("pre-add gap closes immutable basket without charging next leg",()=>{const s=canonicalFull(),p=s.position;p.legs=p.legs.slice(0,3);p.totalMargin=70;p.totalNotional=700;p.remainingNotional=700;p.pendingAdd={confirmedAt:6000000,referencePrice:95,zone:{id:"ema",level:95}};const before=p.legs.length,fees=p.entryFeesPaid;processSimulator(s,current(80,6060000,80),{"1m":[c(6000001,6060000,80,81,79,80)]});assert.equal(s.position,null);assert.equal(s.trades[0].legs.length,before);assert.equal(s.trades[0].entryFeesPaid,fees);});
test("same-version migration recomputes forged totals and weighted average",()=>{const s=canonicalFull();s.position.totalNotional=9;s.position.totalMargin=9;s.position.weightedAverage=999;migrateSimulator(s);const m=migrateSimulator(s);assert.equal(m.position.totalNotional,1500);assert.equal(m.position.totalMargin,150);assert.notEqual(m.position.weightedAverage,999);});
test("same-version malformed remaining leg drops basket fail closed",()=>{const s=canonicalFull();s.position.legs[0].remainingNotional=Infinity;assert.equal(migrateSimulator(s).position,null);});
test("JSON roundtrip preserves canonical open basket after add",()=>{const s=canonicalFull();const m=migrateSimulator(JSON.parse(JSON.stringify(s)));assert.equal(m.position.legs.length,4);assert.equal(m.position.remainingNotional,1500);assert.ok(Number.isFinite(m.position.riskBoundary));});
test("JSON roundtrip reconstructs partial accounting rather than trusting aggregates",()=>{const s=canonicalFull(),p=s.position;p.structuralPartials=[{level:105,type:"ema",reason:"EMA 50",fraction:.25,executed:false}];processSimulator(s,current(80,6060000,104),{"1m":[c(6000001,6060000,104,106,99,104)]});const expected={pnl:p.partials[0].pnl,fee:p.partials[0].fee,remaining:p.remainingNotional};s.bank=p.baselineEquity-p.entryFeesPaid+expected.pnl;const m=migrateSimulator(JSON.parse(JSON.stringify(s)));assert.ok(Math.abs(m.position.realizedPnl-expected.pnl)<1e-8);assert.ok(Math.abs(m.position.exitFeesPaid-expected.fee)<1e-8);assert.ok(Math.abs(m.position.remainingNotional-expected.remaining)<1e-8);});
test("completed basket records canonical candidate and learning evidence",()=>{const s=canonicalFull();processSimulator(s,current(80,6060000,99),{"1m":[c(6000001,6060000,100,101,80,99)]});const t=s.trades[0];assert.ok(Array.isArray(t.candidateIds));assert.deepEqual(Object.keys(t.learning.weightsBefore),Object.keys(WEIGHTS));assert.deepEqual(t.learning.weightsAfter,t.causalEvidence.expectedWeightsAfter);assert.equal(t.evidenceAvailability,"consistent-causal-evidence-v2");});
test("global halt prevents weak macro enabled exposure",()=>{const s=createSimulator();s.bank=800;const r=processSimulator(s,current(70),{"1m":history()},{macroSnapshot:{score:99,stale:false,availableFrom:5999000}});assert.equal(r.halted,true);assert.equal(s.position,null);});
test("strategy version is persisted for schema isolation",()=>assert.equal(createSimulator().strategyVersion,STRATEGY_VERSION));

for(const [score,stale,offset,allowed] of [[80,false,-1,true],[100,false,-1800000,true],[80,true,-1,false],[79,false,-1,false],[100,false,1,false],[NaN,false,-1,false]])test(`macro causal boundary ${score}/${stale}/${offset}`,()=>{const sim=createSimulator();processSimulator(sim,current(70),{"1m":history()},{macroSnapshot:{score,stale,availableFrom:6000000+offset}});assert.equal(Boolean(sim.position),allowed);});
for(const [index,fraction] of BASKET_MARGIN_FRACTIONS.entries())test(`frozen tranche ${index+1} is ${fraction*100}%`,()=>{const p=canonicalFull().position,l=p.legs[index];assert.equal(l.margin,p.baselineEquity*fraction);assert.equal(l.notional,l.margin*10);assert.equal(l.index,index+1);});
for(const side of ["long","short"])test(`${side} modeled liquidation and risk boundaries are finite`,()=>{const p=canonicalFull(side).position;assert.ok(Number.isFinite(p.riskBoundary)&&p.riskBoundary>0);assert.ok(Number.isFinite(p.liquidationBoundary)&&p.liquidationBoundary>0);assert.notEqual(p.riskBoundary,p.liquidationBoundary);});
for(const [tf,maxAge] of [["5m",300000],["15m",900000],["1h",3600000]])test(`${tf} context accepts its exact freshness boundary`,()=>{const bar=c(4000001,406000000),m=current(80,406000000);m[tf].closeTime=406000000-maxAge;const sim=createSimulator();assert.notEqual(processSimulator(sim,m,{"1m":[bar]}).invalidData,true);});
for(const side of ["long","short"])test(`${side} gap beyond hard boundary records cap overshoot honestly`,()=>{const sim=canonicalFull(side),price=side==="long"?50:150;processSimulator(sim,current(side==="long"?80:20,6060000,price),{"1m":[c(6000001,6060000,price,price+1,price-1,price)]});assert.equal(sim.position,null);assert.ok(sim.trades[0].pnl < -100);});
test("pattern candidates are frozen at first basket decision",()=>{const sim=createSimulator(),m=current();m["1m"]={...m["1m"],ema50:102,ema200:100,close:103};processSimulator(sim,m,{"1m":history(c(1,6000000,103,104,102,103))});assert.ok(sim.position.candidateIds.includes("ema-alignment"));});
test("indicator evolution advances only after completed basket",()=>{const sim=canonicalFull();const before=sim.learningSteps;processSimulator(sim,current(80,6060000,99),{"1m":[c(6000001,6060000,100,101,80,99)]});assert.equal(sim.learningSteps,before+1);assert.equal(sim.learning.steps,sim.learningSteps);});
test("executed partial history survives same-version JSON persistence",()=>{const sim=canonicalFull(),p=sim.position;p.structuralPartials=[{level:105,type:"ema",reason:"EMA 50",fraction:.25,executed:true,executedAt:2}];const m=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.equal(m.position.structuralPartials[0].executed,true);});
test("modeled liquidation disclosure is fixed and exchange-qualified",()=>assert.match(open().position.liquidationPolicy,/Modeled cross-margin.*exchange-specific/i));


function withHonestPartial(){const sim=canonicalFull(),p=sim.position;p.structuralPartials=[{level:105,type:"ema",reason:"EMA 50",fraction:.25,executed:false}];processSimulator(sim,current(80,6060000,104),{"1m":[c(6000001,6060000,104,106,99,104)]});return sim;}
test("missing canonical entryFee drops persisted basket",()=>{const sim=canonicalFull();delete sim.position.legs[0].entryFee;assert.equal(migrateSimulator(sim).position,null);});
test("NaN canonical entryFee drops persisted basket",()=>{const sim=canonicalFull();sim.position.legs[0].entryFee=NaN;assert.equal(migrateSimulator(sim).position,null);});
test("injected million partial PnL is rejected",()=>{const sim=withHonestPartial();sim.position.partials[0].pnl=1e6;assert.equal(migrateSimulator(sim).position,null);});
test("duplicate execution slice is rejected",()=>{const sim=withHonestPartial();sim.position.partials.push(structuredClone(sim.position.partials[0]));assert.equal(migrateSimulator(sim).position,null);});
test("overclose allocation is rejected",()=>{const sim=withHonestPartial();sim.position.partials[0].allocations[0].closedNotional=1e9;assert.equal(migrateSimulator(sim).position,null);});
test("negative execution allocation is rejected",()=>{const sim=withHonestPartial();sim.position.partials[0].allocations[0].closedNotional=-1;assert.equal(migrateSimulator(sim).position,null);});
test("partial remaining-state mismatch is rejected",()=>{const sim=withHonestPartial();sim.position.legs[0].remainingNotional+=1;assert.equal(migrateSimulator(sim).position,null);});
test("persisted bank mismatch is rejected rather than normalized",()=>{const sim=withHonestPartial();sim.bank+=1;const m=migrateSimulator(sim);assert.equal(m.position,null);assert.equal(m.bank,1000);});

test("completed final slice survives audited JSON roundtrip",()=>{const sim=canonicalFull();processSimulator(sim,current(80,6060000,99),{"1m":[c(6000001,6060000,100,101,80,99)]});const expected=sim.trades[0].pnl,m=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.equal(m.trades.length,1);assert.ok(Math.abs(m.trades[0].pnl-expected)<1e-8);assert.equal(m.trades[0].partials.at(-1).reason,sim.trades[0].reason);});

for(const side of ["long","short"])test(`${side} tampered entry fill is rejected despite plausible costs`,()=>{const sim=canonicalFull(side);sim.position.legs[0].fillPrice+=.01;assert.equal(migrateSimulator(sim).position,null);});
for(const side of ["long","short"])test(`${side} coordinated exit raw/fill tamper is rejected`,()=>{const sim=withHonestPartial();if(side==="short"){const shortSim=canonicalFull("short"),p=shortSim.position;p.structuralPartials=[{level:95,type:"ema",reason:"EMA 50",fraction:.25,executed:false}];processSimulator(shortSim,current(20,6060000,96),{"1m":[c(6000001,6060000,96,100,94,96)]});Object.assign(sim,shortSim);}const slice=sim.position.partials[0];slice.rawPrice+=1;slice.fillPrice+=1;slice.price=slice.fillPrice;assert.equal(migrateSimulator(sim).position,null);});
for(const side of ["long","short"])test(`${side} honest canonical execution prices survive JSON roundtrip`,()=>{const sim=canonicalFull(side),m=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.ok(m.position);assert.equal(m.position.side,side);});

for(const side of ["long","short"])test(`${side} intrabar chooses first reachable hard-risk boundary`,()=>{const sim=canonicalFull(side),p=sim.position,bar=side==="long"?c(6000001,6060000,100,110,p.liquidationBoundary-1,105):c(6000001,6060000,100,p.liquidationBoundary+1,90,95);processSimulator(sim,current(side==="long"?80:20,6060000,bar.close),{"1m":[bar]});assert.equal(sim.position,null);assert.equal(sim.trades[0].reason,"Hard basket loss boundary");assert.ok(Math.abs(sim.bank-p.effectiveFloor)<1e-8);});
for(const side of ["long","short"])test(`${side} intrabar chooses modeled liquidation when it is first reachable`,()=>{const sim=canonicalFull(side),p=sim.position;p.effectiveFloor=0;const boundary=p.liquidationBoundary,bar=side==="long"?c(6000001,6060000,100,120,boundary-.1,115):c(6000001,6060000,100,boundary+.1,80,85);processSimulator(sim,current(side==="long"?80:20,6060000,bar.close),{"1m":[bar]});assert.equal(sim.trades[0].reason,"Modeled cross-margin liquidation intrabar");assert.ok(Math.abs(sim.trades[0].partials.at(-1).fillPrice-boundary)<1e-8);});
test("first reachable risk boundary wins dual hit before favorable partial",()=>{const sim=canonicalFull("long"),p=sim.position;p.structuralPartials=[{level:110,type:"ema",reason:"EMA 50",fraction:.25,executed:false}];processSimulator(sim,current(80,6060000,105),{"1m":[c(6000001,6060000,100,115,p.liquidationBoundary-1,105)]});assert.equal(sim.trades[0].reason,"Hard basket loss boundary");assert.equal(sim.trades[0].partials.length,1);assert.equal(sim.trades[0].partials[0].reason,"Hard basket loss boundary");});
test("non-hit candle leaves basket open without synthetic liquidation",()=>{for(const side of ["long","short"]){const sim=canonicalFull(side),p=sim.position,bar=side==="long"?c(6000001,6060000,100,103,p.riskBoundary+1,101):c(6000001,6060000,100,p.riskBoundary-1,97,99);processSimulator(sim,current(side==="long"?80:20,6060000,bar.close),{"1m":[bar]});assert.ok(sim.position);assert.equal(sim.trades.length,0);}});
