import test from "node:test";
import assert from "node:assert/strict";
import { calculateMacroImpact, parseComparableMacroValue, scoreMacroEvent } from "../macro-impact.js";
const NOW=Date.UTC(2026,6,14,12); const event=overrides=>({impact:"high",timestamp:NOW+10*60000,actual:"2.5%",forecast:"2.0%",...overrides});
test("parses locale decimals, signs and scale suffixes without guessing grouped forms",()=>{assert.deepEqual(parseComparableMacroValue("2,5%"),{value:2.5,unit:"%"});assert.deepEqual(parseComparableMacroValue("-2,5%"),{value:-2.5,unit:"%"});assert.deepEqual(parseComparableMacroValue("+1.2K"),{value:1200,unit:"number"});assert.deepEqual(parseComparableMacroValue("1,2M"),{value:1200000,unit:"number"});assert.equal(parseComparableMacroValue("1,234.5"),null);assert.equal(parseComparableMacroValue("1,234,567"),null);assert.equal(parseComparableMacroValue("—"),null);assert.equal(parseComparableMacroValue("$2.5B"),null)});
test("missing or contradictory units never create surprise",()=>{assert.equal(scoreMacroEvent(event({actual:"",forecast:"2%"}),NOW).surprise,0);assert.equal(scoreMacroEvent(event({actual:"2%",forecast:"2K"}),NOW).surprise,0)});
test("proximity release window raises intensity",()=>{assert.equal(scoreMacroEvent(event({timestamp:NOW+10*60000,actual:"",forecast:""}),NOW).score,85);assert.equal(scoreMacroEvent(event({timestamp:NOW+2*86400000,actual:"",forecast:""}),NOW).score,55);assert.equal(scoreMacroEvent(event({timestamp:NOW-30*60000,actual:"",forecast:""}),NOW).score,85)});
test("aggregation is bounded and item count cannot manufacture extreme",()=>{const distant=Array.from({length:20},()=>event({impact:"low",timestamp:NOW+2*86400000,actual:"",forecast:""}));assert.equal(calculateMacroImpact(distant,NOW).score,20);const result=calculateMacroImpact([event({actual:"2%",forecast:"2%"})],NOW);assert.equal(result.score,85);assert.equal(result.band,"extreme");assert.match(result.explanation,/No indica dirección/)});
test("duplicate calendar rows never inflate aggregate intensity",()=>{const first=event({title:" IPC de EE.UU. ",currency:"usd",actual:"",forecast:""});const duplicate={...first,title:"ipc   de ee.uu.",currency:"USD"};assert.equal(calculateMacroImpact([first,duplicate],NOW).score,85);assert.equal(calculateMacroImpact([{...first,id:"release-1"},{...duplicate,id:"release-1"}],NOW).score,85)});
test("band boundaries are stable",()=>{assert.equal(calculateMacroImpact([],NOW).band,"low");assert.equal(calculateMacroImpact([event({impact:"medium",timestamp:NOW+5*3600000,actual:"",forecast:""})],NOW).band,"moderate");assert.equal(calculateMacroImpact([event({timestamp:NOW+5*3600000,actual:"",forecast:""})],NOW).band,"high")});
import { readFile } from "node:fs/promises";
test("macro markup exposes meter, continuous ticker and one local refresh timer",async()=>{const [html,css,app]=await Promise.all([readFile(new URL("../index.html",import.meta.url),"utf8"),readFile(new URL("../styles.css",import.meta.url),"utf8"),readFile(new URL("../app.js",import.meta.url),"utf8")]);assert.match(html,/role="meter"[^>]+aria-valuemin="0"[^>]+aria-valuemax="100"/);assert.match(html,/id="macroImpactScore"/);assert.match(app,/track\.append\(group, group\.cloneNode\(true\)\)/);assert.equal(app.match(/setInterval\(\(\) => updateMacroImpact\(lastMacroItems\), 60000\)/g)?.length,1);assert.match(app,/pagehide[^\n]+clearInterval\(macroImpactTimer\)[^\n]+once:true/);assert.match(css,/@keyframes macro-scroll\{to\{transform:translateX\(-50%\)\}\}/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.macro-ticker-track\{animation:none\}/);assert.match(css,/\.macro-ticker-track\{min-width:200%/)});

