import test from "node:test";
import assert from "node:assert/strict";
import { WEIGHTS } from "../strategy.js";
import { createSimulator, getMarkToMarket, migrateSimulator, processSimulator, selectLeverage, SIMULATOR_VERSION, TIMEFRAMES } from "../simulator.js";
const parts=Object.fromEntries(Object.keys(WEIGHTS).map((k,i)=>[k,i%2?-.35:.45]));
const rows=c=>({"5m":c?[c]:[]});
const market=(long=80,close=100,closeTime=1000)=>Object.fromEntries(TIMEFRAMES.map(tf=>[tf,{long,short:100-long,parts,close,closeTime}]));
const candle=(closeTime,low=99,high=102,time=1001)=>({time,closeTime,low,high,open:(low+high)/2,close:(low+high)/2});
test("opens once for an extreme signal",()=>{const s=createSimulator(123);processSimulator(s,market(),rows());const p=s.position;processSimulator(s,market(),rows());assert.equal(s.position,p);assert.ok(Math.abs(p.estimatedLossAtStop-20)<1e-9);assert.equal(s.version,SIMULATOR_VERSION)});
test("takes one profitable 50% partial",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(60,104,2000),rows(candle(2000)));assert.equal(s.position.remainingFraction,.5);assert.equal(s.position.partials.length,1);assert.ok(Math.abs(s.position.realizedPnl-(s.position.capital*.5*.037))<1e-9);assert.ok(Math.abs(s.bank-(1000+s.position.realizedPnl))<1e-9);processSimulator(s,market(60,104,3000),rows(candle(3000,103,104,2001)));assert.equal(s.position.partials.length,1)});
test("losing neutral exit is invalidation",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(54,99,2000),rows(candle(2000,98,101)));assert.equal(s.position,null);assert.equal(s.trades[0].reason,"Signal invalidation");assert.ok(s.trades[0].pnl<0)});
test("learns only on final close",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(60,104,2000),rows(candle(2000)));assert.equal(s.learningSteps,0);processSimulator(s,market(54,103,3000),rows(candle(3000,102,104,2001)));assert.equal(s.position,null);assert.equal(s.learningSteps,1);assert.equal(s.trades[0].partials.length,1);assert.equal(s.trades[0].reason,"Neutral profit exit")});
test("reversal waits for later closed 5m candle",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(20,99,2000),rows(candle(2000,98,101)));assert.equal(s.position,null);assert.equal(s.pendingReversal.side,"short");processSimulator(s,market(20,99,2000),rows(candle(2000,98,101)));assert.equal(s.position,null);processSimulator(s,market(20,98,302000),rows(candle(302000,97,99,2001)));assert.equal(s.position.side,"short");assert.equal(s.position.entryTime,302000)});
test("pending reversal expires without confirmation",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(20,99,2000),rows(candle(2000,98,101)));processSimulator(s,market(50,99,302000),rows(candle(302000,98,100,2001)));assert.equal(s.position,null);assert.equal(s.pendingReversal,null)});
test("stop wins conservatively and fees count once",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(70,102,2000),rows(candle(2000,97,106)));assert.equal(s.trades[0].reason,"Stop 2.5% asset move");assert.ok(Math.abs(s.trades[0].pnl+20)<1e-9);assert.ok(Math.abs(s.bank-980)<1e-9)});
test("mark combines realized and remaining exposure",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(60,104,2000),rows(candle(2000)));const m=getMarkToMarket(s,{close:104});assert.ok(Math.abs(m.realizedPnl-s.position.realizedPnl)<1e-9);assert.ok(Math.abs(m.pnl-(s.position.capital*.5*.037))<1e-9);assert.ok(Math.abs(m.equity-(s.bank+m.pnl))<1e-9);assert.ok(Math.abs(s.bank-(1000+s.position.realizedPnl))<1e-9)});
test("preserves data gap pause",()=>{const s=createSimulator();processSimulator(s,market(),rows());const r=processSimulator(s,market(80,101,20000),rows(candle(20000,99,102,10000)));assert.equal(r.paused,true);assert.equal(s.position.dataGap,true);assert.equal(s.trades.length,0)});
test("safe legacy and corrupt migration",()=>{const legacy={bank:900,weights:{...WEIGHTS},position:{side:"long",entry:100,entryTime:1,dataGap:true},trades:[]};const m=migrateSimulator(legacy,10);assert.equal(m.version,SIMULATOR_VERSION);assert.equal(m.position.remainingFraction,1);assert.equal(m.position.partialTaken,false);assert.deepEqual(m.position.partials,[]);assert.equal(m.position.dataGap,true);assert.equal(migrateSimulator({bank:"bad",weights:{}},42).startedAt,42)});
test("400 adversarial updates remain bounded",()=>{const s=createSimulator();for(let i=0;i<400;i++){const entry=i*3+1,exit=entry+1,long=i%2?20:80;processSimulator(s,market(long,100,entry),rows());const score=long===80?54:46,close=long===80?(i%3?101:99):(i%3?99:101);processSimulator(s,market(score,close,exit),rows(candle(exit,98,102,entry+.1)));s.pendingReversal=null}const values=Object.entries(s.weights);assert.equal(s.learningSteps,400);assert.ok(Math.abs(values.reduce((a,[,v])=>a+v,0)-100)<1e-9);for(const [k,v] of values){assert.ok(Number.isFinite(v));assert.ok(v>=WEIGHTS[k]*.60-1e-9);assert.ok(v<=WEIGHTS[k]*1.40+1e-9)}});


test("55 boundary closes all without synthetic partial",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(55,104,2000),rows(candle(2000)));assert.equal(s.position,null);assert.equal(s.trades[0].partials.length,0);assert.ok(s.trades[0].pnl>0)});
test("62 boundary takes partial but net non-profit does not",()=>{const profitable=createSimulator();processSimulator(profitable,market(),rows());processSimulator(profitable,market(62,104,2000),rows(candle(2000)));assert.equal(profitable.position.remainingFraction,.5);const flat=createSimulator();processSimulator(flat,market(),rows());processSimulator(flat,market(62,100.1,2000),rows(candle(2000,99,101)));assert.equal(flat.position.remainingFraction,1);assert.equal(flat.position.partials.length,0)});
test("long and short use symmetric fixed-notional returns",()=>{const long=createSimulator();processSimulator(long,market(80,100,1000),rows());assert.ok(Math.abs(getMarkToMarket(long,{close:104}).pnl-(long.position.capital*.037))<1e-9);const short=createSimulator();processSimulator(short,market(20,100,1000),rows());assert.ok(Math.abs(getMarkToMarket(short,{close:96}).pnl-(short.position.capital*.037))<1e-9);processSimulator(long,market(70,105,2000),rows(candle(2000,99,105)));processSimulator(short,market(30,95,2000),rows(candle(2000,95,101)));assert.ok(Math.abs(long.trades[0].pnl-(long.trades[0].capital*.047))<1e-9);assert.ok(Math.abs(short.trades[0].pnl-(short.trades[0].capital*.047))<1e-9)});
test("short partial and final accounting is symmetric with long",()=>{const s=createSimulator();processSimulator(s,market(20,100,1000),rows());processSimulator(s,market(40,96,2000),rows(candle(2000,96,101)));assert.ok(Math.abs(s.position.realizedPnl-(s.position.capital*.5*.037))<1e-9);assert.equal(s.position.remainingFraction,.5);assert.equal(s.learningSteps,0);processSimulator(s,market(46,97,3000),rows(candle(3000,96,98,2001)));assert.equal(s.position,null);assert.ok(Math.abs(s.trades[0].pnl-(s.trades[0].capital*(.5*.037+.5*.027)))<1e-9);assert.equal(s.learningSteps,1)});
test("short stop is symmetric with long stop",()=>{const s=createSimulator();processSimulator(s,market(20),rows());processSimulator(s,market(30,102,2000),rows(candle(2000,94,103)));assert.ok(Math.abs(s.trades[0].pnl+20)<1e-9)});
test("reversal needs a real 3 of 4 agreement",()=>{const s=createSimulator();processSimulator(s,market(),rows());const opposite=market(0,99,2000);opposite["4h"].long=50;opposite["4h"].short=50;processSimulator(s,opposite,rows(candle(2000,98,101)));assert.equal(s.pendingReversal.agreement,3);assert.ok(s.pendingReversal.score>=75)});
test("skipped expected reversal candle expires pending state",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(20,99,2000),rows(candle(2000,98,101)));processSimulator(s,market(20,98,602000),rows(candle(602000,97,99,302001)));assert.equal(s.position,null);assert.equal(s.pendingReversal,null)});
test("stale expected candle cannot open a later reversal",()=>{const s=createSimulator();processSimulator(s,market(),rows());processSimulator(s,market(20,99,2000),rows(candle(2000,98,101)));processSimulator(s,market(20,98,602000),{"5m":[candle(302000,97,99,2001),candle(602000,97,99,302001)]});assert.equal(s.position,null);assert.equal(s.pendingReversal,null)});


test("leverage cold start is conservative and deterministic",()=>{const s=createSimulator();const signal={long:80,short:20,agreement:4};const first=selectLeverage(s,signal,{close:100});const second=selectLeverage(s,signal,{close:100});assert.deepEqual(first,second);assert.equal(first.leverage,1);const strong={long:96,short:4,agreement:4};assert.equal(selectLeverage(s,strong,{close:100,bbUpper:101,bbLower:99}).leverage,2)});
test("learned leverage is capped from 1x through 10x",()=>{const s=createSimulator();s.leverageLearning.closedTrades=20;s.leverageLearning.target=99;const d=selectLeverage(s,{long:100,short:0,agreement:4},{close:100,bbUpper:100.5,bbLower:99.5});assert.equal(d.leverage,10);s.leverageLearning.target=-5;assert.equal(selectLeverage(s,{long:100,short:0,agreement:4},{close:100,bbUpper:100.5,bbLower:99.5}).leverage,1)});
test("volatility and loss circuit breakers reduce leverage",()=>{const s=createSimulator();s.leverageLearning.closedTrades=20;s.leverageLearning.target=10;const signal={long:100,short:0,agreement:4};assert.equal(selectLeverage(s,signal,{close:100,high:110,low:90}).leverage,1);s.leverageLearning.lossStreak=2;assert.equal(selectLeverage(s,signal,{close:100,bbUpper:101,bbLower:99}).leverage,1)});
test("leverage never creates a trade without SimpleTrading extreme signal",()=>{const s=createSimulator();s.leverageLearning.closedTrades=50;s.leverageLearning.target=10;processSimulator(s,market(70,100,1000),rows());assert.equal(s.position,null);assert.equal(s.trades.length,0)});
test("risk adjusted learning increases target at most one step after final close",()=>{const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=5;const entry=market(100,100,1000);entry["5m"].bbUpper=101;entry["5m"].bbLower=99;processSimulator(s,entry,rows());assert.equal(s.position.leverage,5);processSimulator(s,market(70,105,2000),rows(candle(2000,99.5,105)));assert.equal(s.leverageLearning.target,6);assert.equal(s.learningSteps,1);assert.equal(s.trades[0].leverageLearning.targetBefore,5);assert.equal(s.trades[0].leverageLearning.targetAfter,6)});
test("loss and drawdown reduce leverage target quickly",()=>{const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=8;const entry=market(100,100,1000);entry["5m"].bbUpper=101;entry["5m"].bbLower=99;processSimulator(s,entry,rows());processSimulator(s,market(80,98,2000),rows(candle(2000,97,101)));assert.equal(s.position,null);assert.equal(s.trades[0].leverage,8);assert.equal(s.leverageLearning.target,7);assert.ok(s.leverageLearning.drawdown>=.019);assert.equal(s.leverageLearning.lossStreak,1)});
test("fees use leveraged notional and partial accounting stays exact",()=>{const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=5;const entry=market(100,100,1000);entry["5m"].bbUpper=101;entry["5m"].bbLower=99;processSimulator(s,entry,rows());processSimulator(s,market(60,104,2000),rows(candle(2000,99,104)));assert.equal(s.position.leverage,5);assert.ok(Math.abs(s.position.realizedPnl-(s.position.capital*.5*.185))<1e-9);assert.ok(Math.abs(s.position.feesPaid-(s.position.capital*.5*.01))<1e-9);assert.ok(Math.abs(s.bank-(1000+s.position.realizedPnl))<1e-9);assert.equal(s.learningSteps,0);processSimulator(s,market(55,103,3000),rows(candle(3000,102,104,2001)));assert.ok(Math.abs(s.trades[0].pnl-(s.trades[0].capital*(.5*.185+.5*.135)))<1e-9);assert.ok(Math.abs(s.trades[0].feesPaid-(s.trades[0].capital*.01))<1e-9);assert.equal(s.learningSteps,1)});
test("leveraged long and short ROI remain symmetric",()=>{for(const [score,exit] of [[100,104],[0,96]]){const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=4;const entry=market(score,100,1000);entry["5m"].bbUpper=101;entry["5m"].bbLower=99;processSimulator(s,entry,rows());const mark=getMarkToMarket(s,{close:exit});assert.ok(Math.abs(mark.pct-14.8)<1e-9);assert.ok(Math.abs(mark.pnl-(s.position.capital*.148))<1e-9);assert.equal(mark.leverage,4)}}); 
test("MAE and MFE are captured candle by candle without temporal leakage",()=>{const s=createSimulator();processSimulator(s,market(100,100,1000),rows());processSimulator(s,market(55,103,2000),rows(candle(2000,99,104)));assert.ok(Math.abs(s.trades[0].maeAsset-.01)<1e-9);assert.ok(Math.abs(s.trades[0].mfeAsset-.04)<1e-9);assert.ok(Number.isFinite(s.trades[0].leverageLearning.riskAdjustedReward))});
test("v2 migration defaults leverage safely without inventing learning history",()=>{const old=createSimulator(10);old.version=2;delete old.leverageLearning;old.position={side:"long",entry:100,entryTime:1,capital:1000,remainingFraction:1,partialTaken:false,partials:[],realizedPnl:0};const m=migrateSimulator(old,20);assert.equal(m.version,3);assert.equal(m.position.leverage,1);assert.match(m.position.leverageReason,/Migrated conservatively/);assert.equal(m.leverageLearning.closedTrades,0);assert.equal(m.leverageLearning.target,1)});


test("10x sizing keeps worst-case estimated loss inside 2% equity budget",()=>{const s=createSimulator();s.leverageLearning.closedTrades=20;s.leverageLearning.target=10;const entry=market(100,100,1000);entry["5m"].bbUpper=100.5;entry["5m"].bbLower=99.5;processSimulator(s,entry,rows());assert.equal(s.position.leverage,10);assert.ok(s.position.estimatedLossAtStop<=s.bank*.02+1e-9);assert.ok(s.position.capital<s.bank);assert.equal(s.position.leverageDecision.marginGuard.compatible,true)});
test("dual-hit candle bounds long excursions at conservative stop fill",()=>{const s=createSimulator();processSimulator(s,market(100),rows());processSimulator(s,market(70,102,2000),rows(candle(2000,97,106)));const t=s.trades[0];assert.equal(t.reason,"Stop 2.5% asset move");assert.equal(t.maeAsset,.025);assert.equal(t.mfeAsset,0);assert.equal(t.excursionQuality,"bounded-at-conservative-stop")});
test("dual-hit candle bounds short excursions at conservative stop fill",()=>{const s=createSimulator();processSimulator(s,market(0),rows());processSimulator(s,market(30,98,2000),rows(candle(2000,94,103)));const t=s.trades[0];assert.equal(t.reason,"Stop 2.5% asset move");assert.equal(t.maeAsset,.025);assert.equal(t.mfeAsset,0)});
test("bank conservation identity holds for leveraged partial and final close",()=>{const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=5;const entry=market(100);entry["5m"].bbUpper=101;entry["5m"].bbLower=99;processSimulator(s,entry,rows());processSimulator(s,market(60,104,2000),rows(candle(2000,99,104)));processSimulator(s,market(55,103,3000),rows(candle(3000,102,104,2001)));assert.ok(Math.abs(s.bank-(s.initialBank+s.trades[0].pnlCurrency))<1e-9);assert.ok(Math.abs(s.trades[0].pnlCurrency-(s.trades[0].capital*s.trades[0].netRoi))<1e-9)});
test("invalid or missing candle data fails closed without mutation",()=>{const s=createSimulator();const incomplete=market();delete incomplete["4h"];const before=s.bank;assert.equal(processSimulator(s,incomplete,rows()).invalidData,true);assert.equal(s.position,null);const invalidRows={"5m":[{...candle(2000),high:NaN}]};assert.equal(processSimulator(s,market(),invalidRows).invalidData,true);assert.equal(s.bank,before);assert.equal(s.position,null)});
test("v2 partial migration reconstructs metrics or marks audit state",()=>{const old=createSimulator();old.version=2;delete old.leverageLearning;old.position={side:"long",entry:100,entryTime:1,capital:1000,remainingFraction:.5,partialTaken:true,realizedPnl:19,partials:[{fraction:.5,price:104,gross:.04,fee:1,pnl:19}],dataGap:false};const m=migrateSimulator(old);assert.equal(m.position.partialTaken,true);assert.ok(Math.abs(m.position.realizedAssetReturn-.02)<1e-9);assert.equal(m.position.feesPaid,1);assert.equal(m.position.legacyMetricsAuditable,true);delete old.position.partials[0].fee;assert.ok(migrateSimulator(old).position)});
test("corrupt persisted invariants are clamped reconstructed or discarded",()=>{const raw=createSimulator();raw.version=3;raw.position={side:"long",entry:100,entryTime:1,capital:1e9,leverage:999,remainingFraction:1,partialTaken:false,partials:[]};raw.trades=[{side:"bad",entry:100,net:1,pnl:1}];raw.leverageLearning={target:NaN,lastLeverage:Infinity,closedTrades:"bad",lossStreak:{}};const m=migrateSimulator(raw);assert.equal(m.position,null);assert.equal(m.trades.length,0);assert.equal(m.leverageLearning.target,1);assert.equal(m.leverageLearning.closedTrades,0)});
test("profitable trade during drawdown never increments loss streak",()=>{const s=createSimulator();s.leverageLearning.closedTrades=5;s.leverageLearning.target=5;s.leverageLearning.peakBank=2000;s.leverageLearning.lossStreak=3;processSimulator(s,market(100),rows());processSimulator(s,market(70,105,2000),rows(candle(2000,100,105)));assert.ok(s.trades[0].netRoi>0);assert.equal(s.leverageLearning.lossStreak,0)});

test("gap beyond maintenance boundary records explicit conservative liquidation",()=>{const s=createSimulator();s.leverageLearning.closedTrades=20;s.leverageLearning.target=10;const entry=market(100);entry["5m"].bbUpper=100.5;entry["5m"].bbLower=99.5;processSimulator(s,entry,rows());const gap={time:1001,closeTime:2000,open:89,high:90,low:88,close:89};processSimulator(s,market(70,89,2000),{"5m":[gap]});assert.equal(s.trades[0].reason,"Conservative liquidation gap");assert.equal(s.trades[0].excursionQuality,"bounded-at-liquidation-gap");assert.ok(s.trades[0].liquidationEvent);assert.ok(s.bank>=0)});

test("0.25% favorable move is not profit after total estimated costs",()=>{const s=createSimulator();processSimulator(s,market(100,100,1000),rows());processSimulator(s,market(62,100.25,2000),rows(candle(2000,99,101)));assert.equal(s.position.partialTaken,false);assert.equal(s.position.partials.length,0)});
test("migrated live capital is preserved and partial PnL is reconstructed, never trusted",()=>{const raw=createSimulator();raw.version=2;raw.bank=1019;delete raw.leverageLearning;raw.position={side:"long",entry:100,entryTime:1000,lastEvaluatedCloseTime:1000,capital:1000,leverage:1,remainingFraction:.5,partialTaken:true,realizedPnl:1e9,partials:[{fraction:.5,price:104,time:1500,gross:999,fee:999,estimatedSlippage:999,pnl:1e9}],parts:{},dataGap:false};const m=migrateSimulator(raw);assert.equal(m.position.capital,1000);assert.equal(m.position.legacyRiskPolicy,"grandfathered-existing-exposure-no-resize");assert.ok(Math.abs(m.position.realizedPnl-18.5)<1e-9);processSimulator(m,market(55,103,2000),rows(candle(2000,102,104,1001)));assert.equal(m.position,null);assert.ok(Math.abs(m.bank-1032.5)<1e-9);assert.ok(Math.abs(m.trades[0].pnlCurrency-32)<1e-9);assert.ok(Number.isFinite(m.trades[0].learning.reward));assert.ok(Number.isFinite(m.trades[0].leverageLearning.riskAdjustedReward))});
test("partial fraction mismatch discards migrated position conservatively",()=>{const raw=createSimulator();raw.version=2;raw.position={side:"long",entry:100,entryTime:1,capital:1000,remainingFraction:.6,partialTaken:true,partials:[{fraction:.5,gross:999,fee:999,estimatedSlippage:999,pnl:1e9}]};assert.equal(migrateSimulator(raw).position,null)});


test("migrated partial without auditable exit price is discarded",()=>{const raw=createSimulator();raw.version=2;raw.position={side:"short",entry:100,entryTime:1,capital:1000,remainingFraction:.5,partialTaken:true,partials:[{fraction:.5,gross:.04,fee:1,pnl:19}]};assert.equal(migrateSimulator(raw).position,null)});
