import test from "node:test";
import assert from "node:assert/strict";
import { analyzePriceVolumeDivergence, buildAccumulationDistribution, buildObv, divergenceGate, selectVolumeSource } from "../volume-divergence.js";
import { TIMEFRAMES, createSimulator, migrateSimulator, processSimulator } from "../simulator.js";

function fixture(kind="neutral", { quote=true, base=true }={}) {
  const rows=[];
  for(let i=0;i<120;i++){
    let close=100,high=101,low=99,volume=(i>=103&&i<=105)?200:(i>=115&&i<=117)?80:100;
    if(kind==="bullish"){
      if(i===104){low=94;high=96;close=95.95;} if(i===116){low=92;high=96;close=95.95;}
      if(i>104&&i<116){close=95+i/10000;high=close+.2;low=close-.2;}
    } else if(kind==="bearish"){
      if(i===104){high=106;low=104;close=104.05;} if(i===116){high=108;low=104;close=104.05;}
      if(i>104&&i<116){close=105-i/10000;high=close+.2;low=close-.2;}
    }
    const row={time:i*60000+1,closeTime:(i+1)*60000,open:close,high,low,close};
    if(base)row.volume=volume;if(quote)row.quoteVolume=volume*100;rows.push(row);
  }return rows;
}
const context=(score,closeTime)=>Object.fromEntries(TIMEFRAMES.map(tf=>[tf,{long:score,short:100-score,close:100,closeTime,parts:{},rsi:50,hist:0}]));

test("OBV is deterministic for up down and flat closes",()=>assert.deepEqual(buildObv([1,2,1,1],[10,20,30,40]),[0,20,-10,-10]));
test("A/D contributes zero when high equals low",()=>assert.deepEqual(buildAccumulationDistribution([{high:1,low:1,close:1}],[50]),[0]));
test("quote volume is preferred and base fallback is explicit",()=>{assert.equal(selectVolumeSource(fixture()).source,"quoteVolume");assert.equal(selectVolumeSource(fixture("neutral",{quote:false})).source,"baseVolume-fallback");});
test("missing and zero volume are unavailable",()=>{assert.equal(analyzePriceVolumeDivergence(fixture("neutral",{quote:false,base:false})).status,"unavailable");const rows=fixture();rows[4].quoteVolume=0;rows[4].volume=0;assert.equal(analyzePriceVolumeDivergence(rows).status,"unavailable");});
test("bullish fixture has confirmed two-of-three divergence and normalized facts",()=>{const r=analyzePriceVolumeDivergence(fixture("bullish"));assert.equal(r.divergence,"bullish");assert.equal(r.strength,80);assert.equal(r.components.rawExhaustion,true);assert.equal(r.components.obvConfirmation,true);assert.equal(r.components.adConfirmation,false);assert.equal(r.pivots.pivot1.relativeVolume,2);assert.equal(r.pivots.pivot2.relativeVolume,.8);});
test("bearish fixture mirrors bullish divergence",()=>{const r=analyzePriceVolumeDivergence(fixture("bearish"));assert.equal(r.divergence,"bearish");assert.ok(r.strength>=70);assert.ok(r.components.obvDelta<0);});
test("same-direction profile is adequate neutral evidence",()=>{const r=analyzePriceVolumeDivergence(fixture());assert.equal(r.status,"neutral");assert.equal(r.divergence,"none");});
test("unconfirmed pivot and mutations after decision cutoff do not alter frozen result",()=>{const rows=fixture("bullish"),before=analyzePriceVolumeDivergence(rows);const later={...rows.at(-1),time:7200001,closeTime:7260000,high:999,low:1,close:500};assert.deepEqual(analyzePriceVolumeDivergence(rows),before);assert.notDeepEqual(analyzePriceVolumeDivergence([...rows,later]),before);});
test("gate vetoes only strong opposite divergence",()=>{assert.equal(divergenceGate("long",analyzePriceVolumeDivergence(fixture("bearish"))).allowed,false);assert.equal(divergenceGate("short",analyzePriceVolumeDivergence(fixture("bullish"))).allowed,false);assert.equal(divergenceGate("long",analyzePriceVolumeDivergence(fixture())).allowed,true);});
test("integration blocks strong conflict and records bounded deduplicated audit",()=>{const sim=createSimulator(),rows=fixture("bearish"),ct=rows.at(-1).closeTime;let result=processSimulator(sim,context(80,ct),{"1m":rows});assert.equal(result.blocked,true);assert.equal(sim.position,null);assert.equal(sim.decisionSnapshots.length,1);result=processSimulator(sim,context(80,ct),{"1m":rows});assert.equal(result.duplicate,true);assert.equal(sim.decisionSnapshots.length,1);});
test("integration allows aligned evidence and freezes entry decision",()=>{const sim=createSimulator(),rows=fixture("bullish"),ct=rows.at(-1).closeTime;assert.equal(processSimulator(sim,context(80,ct),{"1m":rows}).opened,true);assert.equal(sim.position.entryDecision.divergence.divergence,"bullish");});
test("unavailable integration evidence fails closed",()=>{const sim=createSimulator(),rows=fixture("neutral",{quote:false,base:false}),ct=rows.at(-1).closeTime;assert.equal(processSimulator(sim,context(80,ct),{"1m":rows}).blocked,true);assert.equal(sim.position,null);});
test("causal window rejects hidden future, duplicate, missing minute and out-of-order rows",()=>{for(const mutate of [
  rows=>{rows[20]={...rows[20],closeTime:rows.at(-1).closeTime+60000};},
  rows=>{rows[70]={...rows[69]};},
  rows=>{rows.splice(70,1);},
  rows=>{[rows[70],rows[71]]=[rows[71],rows[70]];}
]){const rows=fixture();mutate(rows);assert.equal(analyzePriceVolumeDivergence(rows).status,"unavailable");}});
test("fixed recent window ignores bad volume outside it but rejects it inside",()=>{const old=fixture().slice(0,50).map((r,i)=>({...r,quoteVolume:i?10000:0,volume:i?100:0})),recent=fixture().map(r=>({...r,time:r.time+3000000,closeTime:r.closeTime+3000000}));assert.equal(analyzePriceVolumeDivergence([...old,...recent]).status,"neutral");recent[10].quoteVolume=0;recent[10].volume=0;assert.equal(analyzePriceVolumeDivergence([...old,...recent]).status,"unavailable");});
test("two-of-three strength 60 is detected but does not veto either side",()=>{const weak={...analyzePriceVolumeDivergence(fixture("bullish")),strength:60};assert.equal(weak.status,"detected");assert.equal(divergenceGate("short",weak).allowed,true);assert.equal(divergenceGate("long",weak).allowed,true);});
test("ambiguous detector evidence blocks both sides",()=>{const ambiguous={...analyzePriceVolumeDivergence(fixture("bullish")),divergence:"ambiguous"};assert.equal(divergenceGate("long",ambiguous).allowed,false);assert.equal(divergenceGate("short",ambiguous).allowed,false);});
test("persistence recomputes gate and rejects forged opened, method, time and side",()=>{const rows=fixture("bullish"),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});assert.ok(migrateSimulator(JSON.parse(JSON.stringify(sim))).position);for(const forge of [
  x=>x.position.entryDecision.opened=false,
  x=>x.position.entryDecision.divergence.method="forged",
  x=>x.position.entryDecision.divergence.evaluatedAt-=60000,
  x=>x.position.entryDecision.side="short"
]){const raw=JSON.parse(JSON.stringify(sim));forge(raw);assert.equal(migrateSimulator(raw).position,null);}});
function priorShape(decision,status){const d=decision.divergence;decision.divergence={...d,status,confidence:d.strength};delete decision.divergence.strength;delete decision.divergence.divergenceSchemaVersion;}
test("prior divergence schema migrates aligned and neutral open baskets without accounting reset",()=>{for(const [kind,status] of [["bullish","aligned"],["neutral","neutral"]]){const rows=fixture(kind),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});const bank=sim.bank;priorShape(sim.position.entryDecision,status);priorShape(sim.decisionSnapshots[0],status);const migrated=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.ok(migrated.position);assert.equal(migrated.bank,bank);assert.equal(migrated.position.entryDecision.divergence.divergenceSchemaVersion,2);assert.equal(migrated.position.entryDecision.divergence.strength,kind==="bullish"?80:0);}});
test("prior conflicting and unavailable open evidence fails closed only at basket level",()=>{for(const status of ["conflicting","unavailable"]){const rows=fixture("bullish"),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});assert.ok(sim.position);const bank=sim.bank;priorShape(sim.position.entryDecision,status);priorShape(sim.decisionSnapshots[0],status);if(status==="conflicting"){sim.position.entryDecision.divergence.divergence="bearish";sim.decisionSnapshots[0].divergence.divergence="bearish";}else{sim.position.entryDecision.divergence.volumeSource="unavailable";sim.decisionSnapshots[0].divergence.volumeSource="unavailable";}const migrated=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.equal(migrated.position,null);assert.equal(migrated.bank,bank);}});
test("prior completed divergence evidence migrates canonically and contradictory evidence is dropped without bank reset",()=>{const rows=fixture("bullish"),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});const next={...rows.at(-1),time:ct+1,closeTime:ct+60000,open:.01,high:.02,low:.005,close:.01};processSimulator(sim,context(80,next.closeTime),{"1m":[...rows.slice(1),next]});assert.equal(sim.trades.length,1);priorShape(sim.trades[0].entryDecision,"aligned");const bank=sim.bank,migrated=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.equal(migrated.bank,bank);assert.equal(migrated.trades.length,1);assert.equal(migrated.trades[0].entryDecision.divergence.strength,80);const forged=JSON.parse(JSON.stringify(sim));forged.trades[0].entryDecision.side="short";const rejected=migrateSimulator(forged);assert.equal(rejected.bank,bank);assert.equal(rejected.trades.length,0);});
test("genuine pre-feature v6 open basket preserves accounting with a frozen not-evaluated marker",()=>{const rows=fixture("neutral"),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});const bank=sim.bank;delete sim.position.entryDecision;sim.decisionSnapshots=[];const migrated=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.ok(migrated.position);assert.equal(migrated.bank,bank);assert.deepEqual(migrated.position.entryDecision,{divergenceFeatureSchemaVersion:0,auditStatus:"legacy-pre-divergence",evaluated:false,reason:"not evaluated"});const roundtrip=migrateSimulator(JSON.parse(JSON.stringify(migrated)));assert.deepEqual(roundtrip.position.entryDecision,migrated.position.entryDecision);});
test("genuine pre-feature completed memory preserves 1000 validated trades and excludes legacy markers from check snapshots",()=>{const rows=fixture("bullish"),ct=rows.at(-1).closeTime,sim=createSimulator();processSimulator(sim,context(80,ct),{"1m":rows});const next={...rows.at(-1),time:ct+1,closeTime:ct+60000,open:.01,high:.02,low:.005,close:.01};processSimulator(sim,context(80,next.closeTime),{"1m":[...rows.slice(1),next]});const base=sim.trades[0];delete base.entryDecision;sim.trades=Array.from({length:1000},(_,i)=>({...structuredClone(base),exitTime:base.exitTime-i}));sim.decisionSnapshots=[];const migrated=migrateSimulator(JSON.parse(JSON.stringify(sim)));assert.equal(migrated.trades.length,1000);assert.equal(migrated.decisionSnapshots.length,0);assert.ok(migrated.trades.every(t=>t.entryDecision.auditStatus==="legacy-pre-divergence"));assert.equal(migrated.learningSteps,1000);});
test("present malformed divergence evidence is not mistaken for absent legacy evidence",()=>{const rows=fixture("neutral"),ct=rows.at(-1).closeTime,open=createSimulator();processSimulator(open,context(80,ct),{"1m":rows});const bank=open.bank;open.position.entryDecision={};assert.equal(migrateSimulator(JSON.parse(JSON.stringify(open))).position,null);assert.equal(migrateSimulator(JSON.parse(JSON.stringify(open))).bank,bank);const closed=createSimulator();processSimulator(closed,context(80,ct),{"1m":rows});const next={...rows.at(-1),time:ct+1,closeTime:ct+60000,open:.01,high:.02,low:.005,close:.01};processSimulator(closed,context(80,next.closeTime),{"1m":[...rows.slice(1),next]});closed.trades[0].entryDecision={};const migrated=migrateSimulator(JSON.parse(JSON.stringify(closed)));assert.equal(migrated.trades.length,0);assert.equal(migrated.bank,closed.bank);});
